/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Doctor */
        get: operations["doctor_api_v1_doctor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export */
        post: operations["export_api_v1_jobs__job_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report */
        get: operations["report_api_v1_jobs__job_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Results */
        get: operations["results_api_v1_jobs__job_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/results/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Result */
        post: operations["review_result_api_v1_jobs__job_id__results_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Review Result Legacy
         * @deprecated
         */
        patch: operations["review_result_legacy_api_v1_jobs__job_id__results_review_patch"];
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Job */
        post: operations["resume_job_api_v1_jobs__job_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime Status */
        get: operations["runtime_status_api_v1_runtime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BackendSummary */
        BackendSummary: {
            /** Effective Compute Type */
            effective_compute_type: string;
            /** Effective Device */
            effective_device: string;
            /** Fallback */
            fallback: boolean;
            /** Fallback Reason */
            fallback_reason: string | null;
            /** Requested Device */
            requested_device: string;
        };
        /** CheckResponse */
        CheckResponse: {
            /** Action */
            action: string;
            /** Code */
            code: string;
            /** Detail */
            detail: string;
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /** Required */
            required: boolean;
            /** Severity */
            severity: string;
        };
        /** ConfigRequest */
        ConfigRequest: {
            /**
             * Compute Type
             * @default auto
             */
            compute_type: string;
            /**
             * Device
             * @default auto
             */
            device: string;
            /**
             * Ideal Text Length
             * @default 10
             */
            ideal_text_length: number;
            /**
             * Language
             * @default auto
             */
            language: string;
            /**
             * Max Text Length
             * @default 40
             */
            max_text_length: number;
            /**
             * Min Centroid
             * @default 1000
             */
            min_centroid: number;
            /**
             * Min Duration
             * @default 0.4
             */
            min_duration: number;
            /**
             * Min Rms
             * @default 0.015
             */
            min_rms: number;
            /**
             * Min Text Length
             * @default 2
             */
            min_text_length: number;
            /**
             * Model Size
             * @default small
             */
            model_size: string;
            /**
             * No Speech Threshold
             * @default 0.45
             */
            no_speech_threshold: number;
            /** Output Dir */
            output_dir: string;
            /**
             * Physics Workers
             * @default 4
             */
            physics_workers: number;
            /**
             * Repeat Char Threshold
             * @default 4
             */
            repeat_char_threshold: number;
            /** Source Dir */
            source_dir: string;
            /**
             * Top N
             * @default 1200
             */
            top_n: number;
        };
        /** ConfigResponse */
        ConfigResponse: {
            /** Compute Type */
            compute_type: string;
            /** Device */
            device: string;
            /** Ideal Text Length */
            ideal_text_length: number;
            /** Language */
            language: string;
            /** Max Text Length */
            max_text_length: number;
            /** Min Centroid */
            min_centroid: number;
            /** Min Duration */
            min_duration: number;
            /** Min Rms */
            min_rms: number;
            /** Min Text Length */
            min_text_length: number;
            /** Model Size */
            model_size: string;
            /** No Speech Threshold */
            no_speech_threshold: number;
            /** Output Dir */
            output_dir: string;
            /** Physics Workers */
            physics_workers: number;
            /** Repeat Char Threshold */
            repeat_char_threshold: number;
            /** Source Dir */
            source_dir: string;
            /** Top N */
            top_n: number;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Action */
            action: string;
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** EventResponse */
        EventResponse: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /** Job Id */
            job_id: string;
            /** Message */
            message: string;
            /** Stage */
            stage: string | null;
            /** Timestamp */
            timestamp: string;
            /** Type */
            type: string;
        };
        /** ExportResponse */
        ExportResponse: {
            /** Count */
            count: number;
            /** Files */
            files: {
                [key: string]: string;
            };
        };
        /** FileResultResponse */
        FileResultResponse: {
            /** Duration */
            duration: number | null;
            /** Effective Selected */
            effective_selected: boolean;
            /** Exported Path */
            exported_path: string | null;
            /** Language */
            language: string | null;
            /** No Speech Prob */
            no_speech_prob: number | null;
            /** Reject Code */
            reject_code: string | null;
            /** Reject Detail */
            reject_detail: string | null;
            /** Relative Path */
            relative_path: string;
            /** Review Decision */
            review_decision: string | null;
            /** Review Note */
            review_note: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
            /** Rms */
            rms: number | null;
            /** Score */
            score: number | null;
            /** Spectral Centroid */
            spectral_centroid: number | null;
            /** Status */
            status: string;
            /** Transcription */
            transcription: string | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Api Version
             * @default v1
             */
            api_version: string;
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Version */
            version: string;
        };
        /** JobResponse */
        JobResponse: {
            config: components["schemas"]["ConfigResponse"];
            /** Created At */
            created_at: string;
            /** Current Stage */
            current_stage: string | null;
            /** Error */
            error: string | null;
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Updated At */
            updated_at: string;
        };
        /** ModelResponse */
        ModelResponse: {
            /** Approximate Vram Mb */
            approximate_vram_mb: number | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** RejectionSummary */
        RejectionSummary: {
            /** Config Field */
            config_field: string | null;
            /** Count */
            count: number;
            /** Description */
            description: string;
            /** Title */
            title: string;
        };
        /** ReportResponse */
        ReportResponse: {
            /** Automatic Selected Count */
            automatic_selected_count: number;
            /** Average Duration */
            average_duration: number | null;
            backend: components["schemas"]["BackendSummary"];
            /** Candidate Count */
            candidate_count: number;
            /** Candidate Pass Rate */
            candidate_pass_rate: number;
            /** Error Count */
            error_count: number;
            /** Generated At */
            generated_at: string;
            /** Job Id */
            job_id: string;
            /** Manual Exclude Count */
            manual_exclude_count: number;
            /** Manual Include Count */
            manual_include_count: number;
            /** Rejected Count */
            rejected_count: number;
            /** Rejection Counts */
            rejection_counts: {
                [key: string]: components["schemas"]["RejectionSummary"];
            };
            /** Schema Version */
            schema_version: number;
            /** Selected Count */
            selected_count: number;
            thresholds: components["schemas"]["ThresholdSummary"];
            /** Total Scanned */
            total_scanned: number;
        };
        /** ResourceLeaseResponse */
        ResourceLeaseResponse: {
            /** Acquired At */
            acquired_at: string;
            /** Device Class */
            device_class: string;
            /** Job Id */
            job_id: string;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /** Decision */
            decision: string;
            /** Note */
            note?: string | null;
            /** Relative Path */
            relative_path: string;
        };
        /** RuntimeStatusResponse */
        RuntimeStatusResponse: {
            /** Active Cuda Jobs */
            active_cuda_jobs: number;
            /** Active Jobs */
            active_jobs: number;
            /** Leases */
            leases: components["schemas"]["ResourceLeaseResponse"][];
            /** Max Active Jobs */
            max_active_jobs: number;
            /** Max Cuda Jobs */
            max_cuda_jobs: number;
        };
        /** ThresholdSummary */
        ThresholdSummary: {
            /** Max Text Length */
            max_text_length: number;
            /** Min Centroid */
            min_centroid: number;
            /** Min Duration */
            min_duration: number;
            /** Min Rms */
            min_rms: number;
            /** Min Text Length */
            min_text_length: number;
            /** No Speech Threshold */
            no_speech_threshold: number;
            /** Repeat Char Threshold */
            repeat_char_threshold: number;
            /** Top N */
            top_n: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    doctor_api_v1_doctor_get: {
        parameters: {
            query?: {
                deep?: boolean;
                device?: string;
                model?: string;
            };
            header?: {
                "x-vocalsieve-token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResponse"][];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State or capacity conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Backend unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State or capacity conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Backend unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-vocalsieve-token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"][];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State or capacity conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Backend unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                "x-vocalsieve-token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State or capacity conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Backend unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-vocalsieve-token"?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State or capacity conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Backend unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "x-vocalsieve-token"?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State or capacity conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Backend unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    export_api_v1_jobs__job_id__export_post: {
        parameters: {
            query?: never;
            header?: {
                "x-vocalsieve-token"?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State or capacity conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Backend unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    report_api_v1_jobs__job_id__report_get: {
        parameters: {
            query?: never;
            header?: {
                "x-vocalsieve-token"?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State or capacity conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Backend unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    results_api_v1_jobs__job_id__results_get: {
        parameters: {
            query?: {
                status?: string | null;
                language?: string | null;
                reason?: string | null;
            };
            header?: {
                "x-vocalsieve-token"?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileResultResponse"][];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State or capacity conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Backend unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    review_result_api_v1_jobs__job_id__results_review_post: {
        parameters: {
            query?: never;
            header?: {
                "x-vocalsieve-token"?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileResultResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State or capacity conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Backend unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    review_result_legacy_api_v1_jobs__job_id__results_review_patch: {
        parameters: {
            query?: never;
            header?: {
                "x-vocalsieve-token"?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileResultResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State or capacity conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Backend unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resume_job_api_v1_jobs__job_id__resume_post: {
        parameters: {
            query?: never;
            header?: {
                "x-vocalsieve-token"?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State or capacity conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Backend unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: {
                "x-vocalsieve-token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"][];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State or capacity conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Backend unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    runtime_status_api_v1_runtime_get: {
        parameters: {
            query?: never;
            header?: {
                "x-vocalsieve-token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeStatusResponse"];
                };
            };
            /** @description Authentication failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description State or capacity conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Backend unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
